image: maven:3.8.1-jdk-11

default:
  interruptible: true
  retry: 2


variables:
  # prevent git clean to happen after repo checkout
  #GIT_CLEAN_FLAGS: none
  # maven related
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
  - .m2/repository/
  - target/

stages:
  - deploy

deploy-and-send-tests:
  stage: deploy
  before_script:
  - wget http://ftp.br.debian.org/debian/pool/main/s/sshpass/sshpass_1.06-1_amd64.deb
  - dpkg -i ./sshpass_1.06-1_amd64.deb
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan redstorm.ml >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
  - mkdir ../build
  - cp -TR ../TarockWebsite/ ../build
  - tar -cvf deploy.tar ../build/
  - sshpass -p $PASSWORD_WEBSITE ssh root@redstorm.ml 'rm -r -f /opt/lampp/htdocs/tarock/*'
  - sshpass -p $PASSWORD_WEBSITE scp /builds/eduard240300/Tarock-Java/Tarock/deploy.tar root@redstorm.ml:/opt/lampp/htdocs/tarock/
  - sshpass -p $PASSWORD_WEBSITE ssh root@redstorm.ml 'cd /opt/lampp/htdocs/tarock/ && tar -xvf deploy.tar && rm -r -f deploy.tar && mv ./build/* . && rm -r -f ./build/'
